POC: Refactor reconcilers to be a first-class struct
redhat-openshift-ecosystem/operator-certification-operator pull request #115
Opened 2022-01-17 16:21 UTC by bcrochet

Instead of implementing the reconcilers for each resource as a function,
this instead makes them structs that follow the Reconciler interface,
defined in the internal/reconcilers package.

It also makes the status update be its own reconciler, rather than sprinkling
status updates (which could cause unwanted reconcile failures) all throughout.

Signed-off-by: Brad P. Crochet <brad@redhat.com>

2022-01-17 16:37 UTC, acornett21 commented
When you test, can you send the outputted `json` of the CR? I want to make sure we aren't changing what the UI is showing.

2022-01-17 20:10 UTC, bcrochet commented
> When you test, can you send the outputted `json` of the CR? I want to make sure we aren't changing what the UI is showing.

It has changed slightly. I think the information is still conveyed properly.

```
apiVersion: certification.redhat.com/v1alpha1
kind: OperatorPipeline
metadata:
  creationTimestamp: "2022-01-17T18:04:18Z"
  generation: 1
  name: example
  namespace: default
  resourceVersion: "8405609"
  uid: 53940161-617b-45ce-aa52-00a4c9f5578c
spec:
  gitHubSecretName: github-api-token
  kubeconfigSecretName: kubeconfig
  pyxisSecretName: pyxis-api-secret
status:
  conditions:
  - lastTransitionTime: "2022-01-17T18:04:21Z"
    message: ""
    reason: ReconcileSucceeded
    status: "True"
    type: PipelineDependenciesAvailable
  - lastTransitionTime: "2022-01-17T18:06:06Z"
    message: ""
    reason: ReconcileSucceeded
    status: "True"
    type: KubeConfigSecretAvailable
  - lastTransitionTime: "2022-01-17T18:06:06Z"
    message: ""
    reason: ReconcileSucceeded
    status: "True"
    type: GithubAPISecretAvailable
  - lastTransitionTime: "2022-01-17T18:06:06Z"
    message: ""
    reason: ReconcileSucceeded
    status: "True"
    type: PyxisApiSecretAvailable
  - lastTransitionTime: "2022-01-17T18:30:23Z"
    message: Marketplace ImageStream found
    observedGeneration: 1
    reason: AsExpected
    status: "True"
    type: Ready
  - lastTransitionTime: "2022-01-17T18:32:39Z"
    message: Certified ImageStream found
    observedGeneration: 1
    reason: AsExpected
    status: "True"
    type: CertifiedIndexReady
  - lastTransitionTime: "2022-01-17T18:33:32Z"
    message: Marketplace ImageStream found
    observedGeneration: 1
    reason: AsExpected
    status: "True"
    type: MarketplaceIndexReady
  observedGeneration: 1
```

2022-01-17 21:12 UTC, acornett21 requested changes
I think this refactor makes sense to me. It's more clear than handling errors inline and updating the status in the various reconcilers. Also with this, once other `reconcile` functions are migrated to this patter we would not have to worry as much about `errors` and how they may or may not have been propagated back to the main reconcile function.

2022-01-17 21:12 UTC, acornett21 commented on internal/reconcilers/certified_image_stream.go
> +	certifiedImageStreamAvailable = "CertifiedImageStreamAvailable"
I think these `Available` constants aren't used anymore from what I can tell.

2022-01-17 21:12 UTC, acornett21 commented on internal/reconcilers/marketplace_image_stream.go
> +	marketplaceImageStreamAvailable = "MarketplaceImageStreamAvailable"
Same here.

2022-01-18 18:40 UTC, bcrochet commented on internal/reconcilers/status.go
> +	if errors.IsNotFound(err) {
From what I can tell, it handles the nil case. But it doesn't hurt to add the err != nil. I'll add that shortly.

2022-01-24 12:20 UTC, itroyano commented on controllers/operatorpipeline_controller.go
> +		requeue, err := r.Reconcile(ctx, pipeline)
if/when the reconcilers list gets longer in the future, we could use Goroutines here to launch them.

2022-01-25 19:48 UTC, acornett21 approved these changes

2022-01-26 15:17 UTC, jomkz approved these changes
/lgtm

2022-01-26 18:57 UTC, merged