Update workflows to support the removal of the bundle dir
redhat-openshift-ecosystem/operator-certification-operator pull request #137
Opened 2022-07-19 14:15 UTC by bcrochet

In order to remove the bundle dir from the repo, we need to have
some additional actions occur.

* Run a 'make bundle'
* Add the required labels to annotations.yaml and bundle.Dockerfile
* Make IMAGE_REGISTRY a secret, so that we can test in forks

Signed-off-by: Brad P. Crochet <brad@redhat.com>

2022-07-19 18:43 UTC, acornett21 requested changes

2022-07-19 18:43 UTC, acornett21 commented on .github/workflows/build-release.yml
> +        echo '  com.redhat.openshift.versions: "v4.8-v4.10"' >> bundle/annotations.yaml
This is a TAB right? So that the YAML is indented properly correct?

2022-07-20 12:35 UTC, bcrochet commented on .github/workflows/build-release.yml
> +        echo IMAGE_REPO=$(echo ${{ secrets.IMAGE_REGISTRY }} | cut -d '/' -f 2) >> $GITHUB_ENV
Not copy pasta, but not thinking. Fixing.

2022-07-20 12:36 UTC, bcrochet commented on .github/workflows/build-release.yml
> +        echo IMAGE_REPO=$(echo ${{ secrets.IMAGE_REGISTRY }} | cut -d '/' -f 2) >> $GITHUB_ENV
No. That's actually correct. IMAGE_REGISTRY secret contains 'quay.io/repo'

2022-07-20 12:37 UTC, bcrochet commented on .github/workflows/build-release.yml
> +        echo '  com.redhat.openshift.versions: "v4.8-v4.10"' >> bundle/annotations.yaml
Not a tab... DIdn't think it was a tab.

2022-07-20 12:43 UTC, bcrochet commented on .github/workflows/build-release.yml
> +        echo '  com.redhat.openshift.versions: "v4.8-v4.10"' >> bundle/annotations.yaml
They're spaces in the generated file.

20 20 is two spaces in the first line. And the last.

```
00000060  72 65 67 69 73 74 72 79  2b 76 31 0a 20 20 6f 70  |registry+v1.  op|
00000070  65 72 61 74 6f 72 73 2e  6f 70 65 72 61 74 6f 72  |erators.operator|
00000080  66 72 61 6d 65 77 6f 72  6b 2e 69 6f 2e 62 75 6e  |framework.io.bun|
00000090  64 6c 65 2e 6d 61 6e 69  66 65 73 74 73 2e 76 31  |dle.manifests.v1|
000000a0  3a 20 6d 61 6e 69 66 65  73 74 73 2f 0a 20 20 6f  |: manifests/.  o|
```

2022-07-20 14:20 UTC, acornett21 approved these changes

2022-07-20 14:47 UTC, jomkz approved these changes

2022-07-20 17:02 UTC, merged